# Generated by Django 4.2.28 on 2026-02-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название сайта')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Логотип')),
                ('icon', models.ImageField(upload_to='icon', verbose_name='Иконка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('locate', models.URLField(verbose_name='Ссылка на карту')),
                ('instagram', models.URLField(verbose_name='Ссылка на инстаграм')),
                ('facebook', models.URLField(verbose_name='Ссылка на фейсбук')),
                ('youtube', models.URLField(verbose_name='Ссылка на ютуб')),
                ('whatsapp', models.URLField(verbose_name='Ссылка на ватсап')),
                ('telegram', models.URLField(verbose_name='Ссылка на телеграм')),
            ],
            options={
                'verbose_name': '1) Настройка сайта',
                'verbose_name_plural': '1) Настройки сайта',
            },
        ),
    ]
