# Generated by Django 4.2.28 on 2026-02-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Описание компании')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Время работы')),
                ('about_text', models.TextField(verbose_name='Текст о компании')),
                ('services_title', models.CharField(max_length=100, verbose_name='Заголовок услуг')),
            ],
            options={
                'verbose_name': '2) Информация о компании',
                'verbose_name_plural': '2) Информация о компании',
            },
        ),
    ]
